import { Curso } from '../interfaces/cursoborrable';

export const CURSOS: Curso[] = [
    {
        id: 11,
        codigo: "1324",
        name: 'BIOINGENIERÍA',
        secciones: null,
        rubricas: [
            {
                profesor: "Panini",
                codigo: "123",
                nivel: 1,
                actividad: "actividad0",
                criterio: "competencia0",
                tipo: "otros",
                semana: "semana0",
                ciclo: "ciclo0",
                semestre: "semestre",
                fecha: "fecha",
                status: false,
                cd: "1.1",
                dimensiones: [
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                ]
            },
            {
                profesor: "Panini",
                codigo: "456",
                cd: "1.2",
                nivel: 1,
                actividad: "actividad1",
                criterio: "competencia1",
                tipo: "laboratorio",
                semana: "semana1",
                ciclo: "ciclo1",
                semestre: "semestre",
                fecha: "fecha",
                status: false,
                dimensiones: [
                    {
                        dim: "Descripcion1",
                        excelente: "excelentisimo1",
                        bueno: "bueno1",
                        endesarrollo: "endesarrollo1",
                        noaceptable: "muy mal1",
                    },
                    {
                        dim: "Descripcion1",
                        excelente: "excelentisimo1",
                        bueno: "bueno1",
                        endesarrollo: "endesarrollo1",
                        noaceptable: "muy mal1",
                    },
                    {
                        dim: "Descripcion1",
                        excelente: "excelentisimo1",
                        bueno: "bueno1",
                        endesarrollo: "endesarrollo1",
                        noaceptable: "muy mal1",
                    },
                ]
            },
            {
                profesor: "Panini",
                codigo: "789",
                nivel: 1,
                cd: "1.2",
                actividad: "actividad2",
                criterio: "competencia2",
                tipo: "trabajo",
                semana: "semana2",
                ciclo: "ciclo2",
                semestre: "semestre",
                fecha: "fecha",
                status: true,
                dimensiones: [
                    {
                        dim: "Descripcion2",
                        excelente: "excelentisimo2",
                        bueno: "bueno2",
                        endesarrollo: "endesarrollo2",
                        noaceptable: "muy mal2",
                    },
                    {
                        dim: "Descripcion2",
                        excelente: "excelentisimo2",
                        bueno: "bueno2",
                        endesarrollo: "endesarrollo2",
                        noaceptable: "muy mal2",
                    },
                    {
                        dim: "Descripcion2",
                        excelente: "excelentisimo2",
                        bueno: "bueno2",
                        endesarrollo: "endesarrollo2",
                        noaceptable: "muy mal2",
                    },
                ]
            }
        ],
    },
    {
        id: 12,
        codigo: "1324",
        name: 'CIENCIA DE LA COMPUTACIÓN',
        secciones: null,
        rubricas: [
            {
                profesor: "Panini",
                codigo: "4567",
                cd: "1.4",
                nivel: 1,
                actividad: "actividad",
                criterio: "competencia3",
                tipo: "proyecto",
                semana: "semana3",
                ciclo: "ciclo3",
                semestre: "semestre",
                fecha: "fecha",
                status: false,
                dimensiones: [
                    {
                        dim: "Descripcion3",
                        excelente: "excelentisimo3",
                        bueno: "bueno3",
                        endesarrollo: "endesarrollo3",
                        noaceptable: "muy mal3",
                    },
                    {
                        dim: "Descripcion3",
                        excelente: "excelentisimo3",
                        bueno: "bueno3",
                        endesarrollo: "endesarrollo3",
                        noaceptable: "muy mal3",
                    },
                    {
                        dim: "Descripcion3",
                        excelente: "excelentisimo3",
                        bueno: "bueno3",
                        endesarrollo: "endesarrollo3",
                        noaceptable: "muy mal3",
                    },
                ]
            },
            {
                profesor: "Panini",
                codigo: "456456",
                nivel: 1,
                actividad: "actividad",
                criterio: "competencia4",
                tipo: "proyecto",
                semana: "semana4",
                ciclo: "ciclo4",
                semestre: "semestre",
                fecha: "fecha",
                status: null,
                cd: "2.1",
                dimensiones: [
                    {
                        dim: "Descripcion4",
                        excelente: "excelentisimo4",
                        bueno: "bueno4",
                        endesarrollo: "endesarrollo4",
                        noaceptable: "muy mal4",
                    },
                    {
                        dim: "Descripcion4",
                        excelente: "excelentisimo4",
                        bueno: "bueno4",
                        endesarrollo: "endesarrollo4",
                        noaceptable: "muy mal4",
                    },
                    {
                        dim: "Descripcion4",
                        excelente: "excelentisimo4",
                        bueno: "bueno4",
                        endesarrollo: "endesarrollo4",
                        noaceptable: "muy mal4",
                    },
                ]   
            },
            {
                profesor: "Panini",
                codigo: "45645",
                nivel: 1,
                actividad: "actividad",
                criterio: "competencia3",
                tipo: "trabajo",
                semana: "semana3",
                ciclo: "ciclo6",
                semestre: "semestre",
                fecha: "fecha",
                status: null,
                cd: "2.2",
                dimensiones: [
                    {
                        dim: "Descripcion5",
                        excelente: "excelentisimo5",
                        bueno: "bueno5",
                        endesarrollo: "endesarrollo5",
                        noaceptable: "muy mal5",
                    },
                    {
                        dim: "Descripcion5",
                        excelente: "excelentisimo5",
                        bueno: "bueno5",
                        endesarrollo: "endesarrollo5",
                        noaceptable: "muy mal5",
                    },
                    {
                        dim: "Descripcion5",
                        excelente: "excelentisimo5",
                        bueno: "bueno5",
                        endesarrollo: "endesarrollo5",
                        noaceptable: "muy mal5",
                    },
                ]
            }
        ]
    },
    {
        id: 13,
        codigo: "1324",
        name: 'CIENCIA DE DATOS',
        secciones: null,
        rubricas: [
            {
                profesor: "Panini",
                codigo: "9789",
                nivel: 1,
                actividad: "actividad",
                criterio: "competencia4",
                tipo: "laboratorio",
                semana: "semana4",
                ciclo: "ciclo",
                semestre: "semestre",
                fecha: "fecha",
                status: false,
                cd: "1.1",
                dimensiones: [
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                ]
            },
            {
                profesor: "Panini",
                codigo: "9789",
                nivel: 1,
                actividad: "actividad",
                criterio: "competencia5",
                tipo: "trabajo",
                semana: "semana5",
                ciclo: "ciclo",
                semestre: "semestre",
                fecha: "fecha",
                status: null,
                cd: "1.1",
                dimensiones: [
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                ]
            },
            {
                profesor: "Panini",
                codigo: "4564565",
                nivel: 1,
                actividad: "actividad",
                criterio: "competencia6",
                tipo: "laboratorio",
                semana: "semana6",
                ciclo: "ciclo",
                semestre: "semestre",
                fecha: "fecha",
                status: null,
                cd: "1.1",
                dimensiones: [
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },

                ]
            }
        ]
    },
    {
        id: 13,
        codigo: "1324",
        name: 'CIENCIA DE DATOS',
        secciones: null,
        rubricas: [
            {
                profesor: "Panini",
                codigo: "qweqwe",
                nivel: 1,
                actividad: "actividad",
                criterio: "competencia7",
                tipo: "trabajo",
                semana: "semana7",
                ciclo: "ciclo",
                semestre: "semestre",
                fecha: "fecha",
                status: null,
                cd: "1.1",
                dimensiones: [
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },

                ]
            },
            {
                profesor: "Panini",
                codigo: "asdasd",
                nivel: 1,
                actividad: "actividad",
                criterio: "competencia8",
                tipo: "trabajo",
                semana: "semana8",
                ciclo: "ciclo",
                semestre: "semestre",
                fecha: "fecha",
                status: null,
                cd: "1.1",
                dimensiones: [
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },

                ]
            },
            {
                profesor: "Panini",
                codigo: "zxczx",
                nivel: 1,
                actividad: "actividad",
                criterio: "competencia9",
                tipo: "trabajo",
                semana: "semana9",
                ciclo: "ciclo",
                semestre: "semestre",
                fecha: "fecha",
                status: null,
                cd: "1.1",
                dimensiones: [
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },

                ]
            }
        ]
    },
    {
        id: 11,
        codigo: "1324",
        name: 'BIOINGENIERÍA',
                secciones: null,
        rubricas: [
            {
                profesor: "Panini",
                codigo: "123",
                cd: "1.1",
                nivel: 1,
                actividad: "actividad0",
                criterio: "competencia0",
                tipo: "otros",
                semana: "semana0",
                ciclo: "ciclo0",
                semestre: "semestre",
                fecha: "fecha",
                status: null,
                dimensiones: [
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                    {
                        dim: "Descripcion0",
                        excelente: "excelentisimo0",
                        bueno: "bueno0",
                        endesarrollo: "endesarrollo",
                        noaceptable: "muy mal",
                    },
                ]
            },
            {
                profesor: "Panini",
                codigo: "456",
                nivel: 1,
                cd: "1.2",
                actividad: "actividad1",
                criterio: "competencia1",
                tipo: "laboratorio",
                semana: "semana1",
                ciclo: "ciclo1",
                semestre: "semestre",
                fecha: "fecha",
                status: null,
                dimensiones: [
                    {

                        dim: "Descripcion1",
                        excelente: "excelentisimo1",
                        bueno: "bueno1",
                        endesarrollo: "endesarrollo1",
                        noaceptable: "muy mal1",
                    },
                    {
                        dim: "Descripcion1",
                        excelente: "excelentisimo1",
                        bueno: "bueno1",
                        endesarrollo: "endesarrollo1",
                        noaceptable: "muy mal1",
                    },
                    {
                        dim: "Descripcion1",
                        excelente: "excelentisimo1",
                        bueno: "bueno1",
                        endesarrollo: "endesarrollo1",
                        noaceptable: "muy mal1",
                    },
                ]
            },
            {
                profesor: "Panini",
                codigo: "789",
                nivel: 1,
                actividad: "actividad2",
                criterio: "competencia2",
                tipo: "trabajo",
                semana: "semana2",
                ciclo: "ciclo2",
                semestre: "semestre",
                fecha: "fecha",
                cd: "1.3",
                status: null,
                dimensiones: [
                    {
                        dim: "Descripcion2",
                        excelente: "excelentisimo2",
                        bueno: "bueno2",
                        endesarrollo: "endesarrollo2",
                        noaceptable: "muy mal2",
                    },
                    {
                        dim: "Descripcion2",
                        excelente: "excelentisimo2",
                        bueno: "bueno2",
                        endesarrollo: "endesarrollo2",
                        noaceptable: "muy mal2",
                    },
                    {
                        dim: "Descripcion2",
                        excelente: "excelentisimo2",
                        bueno: "bueno2",
                        endesarrollo: "endesarrollo2",
                        noaceptable: "muy mal2",
                    },
                ],
            },
        ],
    },
];