package com.utec.software.services;

import org.eclipse.microprofile.config.inject.ConfigProperty;

public class DBUtecService {
    @ConfigProperty(name = "utec.datasource.username")
    String dbUsername;

    @ConfigProperty(name = "utec.datasource.password")
    String dbPassword;

    @ConfigProperty(name = "utec.datasource.jdbc.url")
    String dbUrl;

    

    static final String QUERYCARRERAS = "SELECT UNIQUE P.DESCRIPCIONLARGA AS CARRERA FROM PROGRAMACION.PRO_MALLA_VIGENTE VI INNER JOIN PROGRAMACION.PRO_PERIODORANGO PR ON PR.CODPERIODORANGO = VI.CODPERIODORANGO INNER JOIN CONFIGURACION.CON_MALLA ML ON ML.CODMALLA = VI.CODMALLA INNER JOIN CONFIGURACION.CON_PRODUCTO P ON P.CODPRODUCTO = ML.CODPRODUCTO WHERE PR.ESVIGENTE = 1 AND VI.ISDELETED ='N'AND P.CODPROGRAMA = 1";
    static final String QUERYCURSO = "SELECT UNIQUE ACT.DESCRIPCIONLARGA AS CURSO, ACT.IDACTIVIDAD AS CODCURSO FROM PROGRAMACION.PRO_CURSO_PERIODO PE INNER JOIN CONFIGURACION.CON_ACTIVIDAD ACT ON ACT.CODACTIVIDAD = PE.CODCURSO AND ACT.ISDELETED ='N' INNER JOIN PROGRAMACION.PRO_CURSO_SECCION SEC ON SEC.CODCURSOPERIODO = PE.CODCURSOPERIODO AND SEC.ISDELETED ='N' INNER JOIN PROGRAMACION.PRO_CURSO_SESION SES ON SES.CODCURSOSECCION = SEC.CODCURSOSECCION AND SES.ISDELETED ='N' INNER JOIN GENERAL.GEN_MAESTRO_TABLAS_DETALLE SECCIONMTD ON SECCIONMTD.CODMAESTROTABLASDETALLE = SEC.CODSECCIONMTD AND SECCIONMTD.ISDELETED = 'N' INNER JOIN GENERAL.GEN_MAESTRO_TABLAS_DETALLE SESIONMTD ON SESIONMTD.CODMAESTROTABLASDETALLE = SES.CODTIPOSESIONMTD AND SESIONMTD.ISDELETED = 'N' WHERE PE.CODPERIODORANGO = 503 ORDER BY 2 ASC";
    static final String QUERYPROFES = "SELECT DISTINCT PERSONA.CODPERSONA, UTEC.GET_NOMBRES_PERSONA (PERSONA.CODPERSONA) AS DOCENTE, persona.USERNAME as correo FROM PROGRAMACION.PRO_CURSO_PERIODO PE INNER JOIN CONFIGURACION.CON_ACTIVIDAD ACT ON ACT.CODACTIVIDAD = PE.CODCURSO AND ACT.ISDELETED ='N' INNER JOIN PROGRAMACION.PRO_CURSO_SECCION SEC ON SEC.CODCURSOPERIODO = PE.CODCURSOPERIODO AND SEC.ISDELETED ='N' INNER JOIN PROGRAMACION.PRO_CURSO_SESION SES ON SES.CODCURSOSECCION = SEC.CODCURSOSECCION AND SES.ISDELETED ='N' INNER JOIN GENERAL.GEN_MAESTRO_TABLAS_DETALLE SECCIONMTD ON SECCIONMTD.CODMAESTROTABLASDETALLE = SEC.CODSECCIONMTD AND SECCIONMTD.ISDELETED = 'N' INNER JOIN GENERAL.GEN_MAESTRO_TABLAS_DETALLE SESIONMTD ON SESIONMTD.CODMAESTROTABLASDETALLE = SES.CODTIPOSESIONMTD AND SESIONMTD.ISDELETED = 'N' INNER JOIN GENERAL.GEN_PERSONA PERSONA ON PERSONA.CODPERSONA = SES.CODDOCENTE INNER JOIN GENERAL.GEN_PERSONA PERSONA2 ON PERSONA2.CODPERSONA = PE.CODCOORDINADOR INNER JOIN GENERAL.GEN_EMPLEADO EMP ON EMP.CODEMPLEADO = PERSONA.CODPERSONA INNER JOIN PROGRAMACION.PRO_PERIODO PERIODO ON PERIODO.CODPERIODO = PE.CODPERIODORANGO WHERE PE.CODPERIODORANGO =503 ORDER BY 2 ASC";
    static final String QUERYCALIDAD ="SELECT CODEMPLEADO, NOMBRECOMPLETOAI, GEN_PERSONA.USERNAME FROM GENERAL.GEN_AREA_FUNCIONAL, GENERAL.GEN_EMPLEADO_AREAFUNCIONAL, GENERAL.GEN_PERSONA WHERE GEN_AREA_FUNCIONAL.CODAREAFUNCIONAL = GEN_EMPLEADO_AREAFUNCIONAL.CODAREAFUNCIONAL AND CODEMPLEADO = CODPERSONA AND GEN_AREA_FUNCIONAL.DESCRIPCORTA = 'Calidad Educativa'";
    static final String QUERYALUMNOS = "SELECT IDALUMNO,NOMBRECOMPLETOAI, GEN_PERSONA.USERNAME FROM GENERAL.GEN_PERSONA, GENERAL.GEN_ALUMNO WHERE CODALUMNO = CODPERSONA order by IDALUMNO";
    static final String QUERYSECCION = "SELECT UNIQUE SECCIONMTD.DESCRIPCIONLARGA AS SECCION, PERIODO.DESCRIPCIONLARGA AS PERIODO FROM PROGRAMACION.PRO_CURSO_PERIODO PE INNER JOIN CONFIGURACION.CON_ACTIVIDAD ACT ON ACT.CODACTIVIDAD = PE.CODCURSO AND ACT.ISDELETED ='N' INNER JOIN PROGRAMACION.PRO_CURSO_SECCION SEC ON SEC.CODCURSOPERIODO = PE.CODCURSOPERIODO AND SEC.ISDELETED ='N' INNER JOIN PROGRAMACION.PRO_CURSO_SESION SES ON SES.CODCURSOSECCION = SEC.CODCURSOSECCION AND SES.ISDELETED ='N' INNER JOIN GENERAL.GEN_MAESTRO_TABLAS_DETALLE SECCIONMTD ON SECCIONMTD.CODMAESTROTABLASDETALLE = SEC.CODSECCIONMTD AND SECCIONMTD.ISDELETED = 'N' INNER JOIN GENERAL.GEN_MAESTRO_TABLAS_DETALLE SESIONMTD ON SESIONMTD.CODMAESTROTABLASDETALLE = SES.CODTIPOSESIONMTD AND SESIONMTD.ISDELETED = 'N' INNER JOIN PROGRAMACION.PRO_PERIODO PERIODO ON PERIODO.CODPERIODO = PE.CODPERIODORANGO WHERE PE.CODPERIODORANGO =503 ORDER BY 1 ASC";

}
